### ISSUE TITLE
Problem in all option

### ISSUE THREAD

**Issue by RyukSniper** [andli/pymkm#10]
hi, i have this problem, when I go to click on one of the options
Action number: 4
Traceback (most recent call last):
  File "C:\Users\Samuele\Desktop\Samuele\pymkm-master\newpymkm\main.py", line 19, in <module>
    main()
  File "C:\Users\Samuele\Desktop\Samuele\pymkm-master\newpymkm\main.py", line 15, in main
    app.start()
  File "C:\Users\Samuele\Desktop\Samuele\pymkm-master\newpymkm\pymkm_app.py", line 97, in start
    menu.show()
  File "C:\Users\Samuele\Desktop\Samuele\pymkm-master\newpymkm\micro_menu.py", line 38, in show
    func(**kwargs)
  File "C:\Users\Samuele\Desktop\Samuele\pymkm-master\newpymkm\pymkmapi.py", line 25, in wrapper
    return_value = func(*arg, **kwargs)
  File "C:\Users\Samuele\Desktop\Samuele\pymkm-master\newpymkm\pymkm_app.py", line 202, in find_deals_from_user
    self.report("find deals from user")
  File "C:\Users\Samuele\Desktop\Samuele\pymkm-master\newpymkm\pymkm_app.py", line 48, in report
    if ALLOW_REPORTING and not self.config['dev_mode']:
KeyError: 'dev_mode'
how i can resolve this error?

**Comment by andli** [comment]
Fixed, pushing new version. Thank you for reporting.
