### ISSUE TITLE
Clean up suggestion is not working

### ISSUE THREAD

**Issue by Guibod** [andli/pymkm#28]
# Context
Option 6 `6: Wantslists cleanup suggestions` crashes

## Expected result
Avoid a crash

## Actual result
```
(3.6.9/envs/pymkm) ➜  pymkm git:(master) ✗ python pymkm.py
╭─── PyMKM 2.0.4 ────────────────────────────────────────╮
│ 1: Update stock prices                                 │
│ 2: Update price for a product                          │
│ 3: List competition for a product                      │
│ 4: Find deals from a user                              │
│ 5: Show top 20 expensive items in stock                │
│ 6: Wantslists cleanup suggestions                      │
│ 7: Show account info                                   │
│ 8: Clear entire stock (WARNING)                        │
│ 9: Import stock from list.csv                          │
│ 10: Track price data to prices.csv                      │
│ 0: Exit                                                │
├────────────────────────────────────────────────────────┤
│ API calls used today: 1073/5000                        │
╰────────────────────────────────────────────────────────╯
Action number: 6
This will show items in your wantslists you have already received.
Gettings wantslists from Cardmarket...
Wantslists cached (21 items).
Wantslists_Lists cached (21 items).
Gettings received orders from Cardmarket...
Matching received purchases with wantslists...
N/A% (0 of 179) |                                                                                                                                          | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "pymkm.py", line 51, in <module>
    main()
  File "pymkm.py", line 46, in main
    app.start(args)
  File "/Users/guillaume/dev/pymkm/pymkm/pymkm_app.py", line 184, in start
    break_signal = menu.show()
  File "/Users/guillaume/.pyenv/versions/3.6.9/envs/pymkm/lib/python3.6/site-packages/micromenu.py", line 48, in show
    func(**kwargs)
  File "/Users/guillaume/dev/pymkm/pymkm/pymkm_app.py", line 787, in clean_purchased_from_wantslists
    "wantlist_name": wantslists[key],
IndexError: list index out of range
```

## Possible Fix
`pymkm/pymkm_app.py:785` needs a better wantlist lookup

**Comment by andli** [comment]
Thanks @Guibod I will look into it and accept your PR if applicable. :)

**Comment by andli** [comment]
I am testing 2.0.5 now which will contain this fix. If you are interested please join the pymkm discord to continue the discussion there: https://discord.gg/hhDsVPy55h
Thanks again!
