### ISSUE TITLE
Issue with List Competition for Card

### ISSUE THREAD

**Issue by DaveBracknell** [andli/pymkm#5]
Hi,
Might be user error but I follow the example in your readme for hydroid I get the following error:
Action number: 3
Search card name:
hydroid
Foil? [y/n]:
n
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 15, in main
    app.start()
  File "D:\Temp\PYMKM2\pymkm_app.py", line 65, in start
    search_string, is_foil, api=self.api)
  File "D:\Temp\PYMKM2\pymkmapi.py", line 25, in wrapper
    return_value = func(*arg, **kwargs)
  File "D:\Temp\PYMKM2\pymkm_app.py", line 191, in list_competition_for_product
    product = products[0]
IndexError: list index out of range

(base) D:\Temp\PYMKM2>
(base) D:\Temp\PYMKM2>

Using Python 3.7.1 anaconda environment

I've managed to get the get_product working but not this piece.
Apologies if user error.

**Comment by andli** [comment]
Confirmed that this is a bug, will fix asap. Thanks for reporting! :)

**Comment by andli** [comment]
Did this work out allright @DaveBracknell ?
