### ISSUE TITLE
Error while search for deals from user

### ISSUE THREAD

**Issue by rubenroques** [andli/pymkm#9]
Hi,

Today I got this error while trying to search for some deals:

```
Searching top X expensive cards for deals, choose X (1-539):
300
 25% (76 of 300) |#########################################                                                                                                                         | Elapsed Time: 0:00:25 ETA:   0:01:17Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 15, in main
    app.start()
  File "/Users/ruben/Downloads/pymkm/pymkm_app.py", line 97, in start
    menu.show()
  File "/Users/ruben/Downloads/pymkm/micro_menu.py", line 38, in show
    func(**kwargs)
  File "/Users/ruben/Downloads/pymkm/pymkmapi.py", line 25, in wrapper
    return_value = func(*arg, **kwargs)
  File "/Users/ruben/Downloads/pymkm/pymkm_app.py", line 232, in find_deals_from_user
    expansion = p['product']['expansion']['enName']
KeyError: 'expansion'
```

Thanks for the great tool!

**Comment by andli** [comment]
Hello! Could you please tell me which version of pymkm you are using and which user you were targeting?

**Comment by andli** [comment]
@rubenroques I hope you problem was solved, please download the latest version and verify. :)

**Comment by rubenroques** [comment]
It's working, thanks!
